module.exports = {
  'object-shorthand': [1],
  'no-console': 0,
  'no-constant-condition': 1,
  'no-debugger': 2,
  'no-dupe-keys': 2,
  'no-empty-character-class': 2,
  'no-ex-assign': 2,
  'no-extra-boolean-cast': 1,
  'no-func-assign': 1,
  'no-invalid-regexp': 2,
  'no-unsafe-negation': 2,
  'no-obj-calls': 2,
  'no-sparse-arrays': 2,
  'no-unreachable': 1,
  'use-isnan': 2,
  'valid-typeof': 2,
  'guard-for-in': 1,
  'no-labels': [1, { allowLoop: true }],
  'no-eval': 1,
  'no-extra-bind': 1,
  'no-implied-eval': 1,
  'no-irregular-whitespace': 1,
  'no-lone-blocks': 1,
  'no-global-assign': 2,
  'no-new-wrappers': 2,
  'no-octal': 1,
  'no-octal-escape': 1,
  'no-proto': 2,
  'no-redeclare': 2,
  'no-self-compare': 2,
  'no-unneeded-ternary': 2,
  'no-with': 2,
  'no-delete-var': 1,
  'no-dupe-args': 2,
  'no-duplicate-case': 2,
  'no-label-var': 1,
  'no-shadow': 1,
  'no-shadow-restricted-names': 2,
  'no-undef': 2,
  'no-undef-init': 1,
  'no-unused-vars': [1, { vars: 'all', args: 'none' }],
  'new-parens': 2,
  'func-call-spacing': 2,
  'no-trailing-spaces': 1,
  'no-extra-parens': [2, 'functions'],
  'no-mixed-spaces-and-tabs': 2,
  'semi-spacing': 2,
  'computed-property-spacing': [2, 'never'],
  'max-len': [1, 120, 4, { ignoreUrls: true, ignoreComments: true }],
  'dot-notation': [2, { allowKeywords: true, allowPattern: '^[a-z]+(_[a-z]+)+$' }],
  'arrow-spacing': 2,
  'constructor-super': 2,
  'no-confusing-arrow': 2,
  'no-class-assign': 2,
  'no-const-assign': 2,
  'no-dupe-class-members': 2,
  'no-this-before-super': 2,
  'no-duplicate-imports': 1,
  'unicode-bom': 2,
};
