module.exports = {
  'import/newline-after-import': 2,
  'import/named': 2,
  'import/default': 2,
  'import/namespace': 2,
  'import/no-restricted-paths': 0,
  'import/no-dynamic-require': 0,
  'import/no-internal-modules': 0,
  'import/no-webpack-loader-syntax': 1,
  'import/export': 2,
  'import/no-named-as-default': 0,
  'import/no-named-as-default-member': 2,
  'import/no-deprecated': 2,
  'import/unambiguous': 0,
  'import/no-amd': 0,
  'import/no-duplicates': 2,
  'import/no-namespace': 0,
  'import/prefer-default-export': 0,
  'import/max-dependencies': 0,
  'import/no-unassigned-import': 0,
};
